import {
  IconAvocado,
  IconBeerFilled,
  IconBottleFilled,
  IconBowl,
  IconBuildingStore,
  IconBurger,
  IconCandy,
  IconChefHatFilled,
  IconCoffee,
  IconEggFriedFilled,
  IconFish,
  IconGlassFullFilled,
  IconHome,
  IconIceCream2,
  IconMilkshake,
  IconMusic,
  IconPizza,
  IconRating18Plus,
  IconSoup,
  IconWheat,
} from '@tabler/icons-react-native';

export const PinIcons = [
  { name: 'Home', component: IconHome },
  { name: 'Avocado', component: IconAvocado },
  { name: 'Store', component: IconBuildingStore },
  { name: 'Beer', component: IconBeerFilled },
  { name: 'Glass Full', component: IconGlassFullFilled },
  { name: 'Bottle', component: IconBottleFilled },
  { name: 'Chef Hat', component: IconChefHatFilled },
  { name: 'Ice Cream', component: IconIceCream2 },
  { name: 'Candy', component: IconCandy },
  { name: 'Wheat', component: IconWheat },
  { name: 'Burger', component: IconBurger },
  { name: 'Bowl', component: IconBowl },
  { name: 'Coffee', component: IconCoffee },
  { name: 'Egg Fried', component: IconEggFriedFilled },
  { name: 'Pizza', component: IconPizza },
  { name: 'Soup', component: IconSoup },
  { name: 'Milkshake', component: IconMilkshake },
  { name: 'Fish', component: IconFish },
  { name: 'Rating 18+', component: IconRating18Plus },
  { name: 'Music', component: IconMusic },
];
